name: PHPUnit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --default-authentication-plugin=mysql_native_password

    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']
        wordpress-versions: ['latest', '6.6', '6.5', '6.4', '6.3']

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mysql, mysqli
          coverage: xdebug
          tools: composer, phpunit

      - name: Install dependencies
        run: composer install

      - name: Install WordPress Test Suite
        run: |
          bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wordpress-versions }}

      - name: Run PHPUnit
        run: composer test