name: Generate Translations

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
      - '**.js'

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: wp-cli

      - name: Generate POT file
        run: wp i18n make-pot . languages/litesurveys.pot --exclude="node_modules/,vendor/,tests/"

      - name: Generate JSON translations for JavaScript
        run: wp i18n make-json languages --no-purge

      - name: Commit translation files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update translation files"
          file_pattern: 'languages/*'
          commit_user_name: "GitHub Action"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Action <actions@github.com>"